#2020-05-08 11：58
server:
  port: 8081
  servlet:
    context-path: /springBootMybatis
  tomcat:
    uri-encoding: UTF-8


spring:
  #数据库配置
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    #新版数据库驱动使用com.mysql.cj.jdbc.Driver    旧版com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #连接池名称，默认HikariPool-1
      pool-name: KevinHikariPool
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 12
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 500000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      #连接测试查询
      connection-test-query: SELECT 1


  #thymeleaf是一种模板语言，可以动态或者静态显示文本内容
  thymeleaf:
    cache: false             #热部署
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    #excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    #reactive:
      #max-chunk-size:
      #media-types:
    servlet:
      content-type: text/html
    suffix: .html
    #template-resolver-order:
    #view-names:







  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

mybatis:
  #这里是实体类的位置，#实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.hegg.springboot.model
  type-aliases-package: com.hegg.springboot.model
  #把xml文件放在com.XX.mapper.*中可能会出现找不到的问题，这里把他放在resource下的mapper中
  mapper-locations: classpath:mapper/*.xml

#分页插件
pagehelper:
  helperDialect: mysql                           #分页插件方言选择
  reasonable: true                               #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
  supportMethodsArguments: true
